
import numpy as np
import pandas as pd


class dictionaries:

    def __init__(self):
        self.tbm_column_translation = {
    '时间戳': 'timestamp',
    '运行时间-time': 'operation_time',
    '桩号-chainages': 'chainage',
    '前点偏差X': 'front_point_deviation_X',
    '前点偏差Y': 'front_point_deviation_Y',
    '前盾俯仰角': 'front_shield_pitch_angle',
    '前盾滚动角': 'front_shield_roll_angle',
    '主液压油箱温度': 'main_hydraulic_tank_temp',
    '液压油箱温度预警设置': 'hydraulic_tank_temp_warning_setting',
    '液压油箱温度报警设置': 'hydraulic_tank_temp_alarm_setting',
    '温度误差设置': 'temperature_error_setting',
    '左侧护盾压力': 'left_shield_pressure',
    '右侧护盾压力': 'right_shield_pressure',
    '顶护盾压力': 'top_shield_pressure',
    '左侧楔形油缸压力': 'left_wedge_cylinder_pressure',
    '右侧楔形油缸压力': 'right_wedge_cylinder_pressure',
    '左侧扭矩油缸伸出压力': 'left_torque_cylinder_extend_pressure',
    '左侧扭矩油缸回收压力': 'left_torque_cylinder_retract_pressure',
    '右侧扭矩油缸伸出压力': 'right_torque_cylinder_extend_pressure',
    '右侧扭矩油缸回收压力': 'right_torque_cylinder_retract_pressure',
    '左侧后支撑压力': 'left_rear_support_pressure',
    '右侧后支撑压力': 'right_rear_support_pressure',
    '撑靴压力': 'shoe_pressure',
    '左侧护盾位移': 'left_shield_displacement',
    '右侧护盾位移': 'right_shield_displacement',
    '左侧扭矩油缸位移': 'left_torque_cylinder_displacement',
    '右侧扭矩油缸位移': 'right_torque_cylinder_displacement',
    '内循环水罐温度': 'internal_cooling_tank_temp',
    '内循环水罐液位': 'internal_cooling_tank_level',
    '冷水箱温度': 'cold_water_tank_temp',
    '冷水箱液位': 'cold_water_tank_level',
    '热水箱温度': 'hot_water_tank_temp',
    '热水箱液位': 'hot_water_tank_level',
    '刀盘喷水压力': 'cutterhead_spray_pressure',
    '刀盘喷水增压泵压力': 'cutterhead_booster_pump_pressure',
    '污水箱压力检测': 'wastewater_tank_pressure',
    'TBM外水进水温度': 'tbm_external_inlet_water_temp',
    'TBM主冷却器进水温度': 'tbm_main_cooler_inlet_temp',
    '暖水泵压力': 'warm_water_pump_pressure',
    '冷水泵压力': 'cold_water_pump_pressure',
    '内水泵压力': 'internal_water_pump_pressure',
    '变频器1温度': 'inverter1_temp',
    '变频器2温度': 'inverter2_temp',
    '暖水箱自动排水温度设置': 'warm_water_tank_drain_temp_setting',
    '二次风机频率设置': 'secondary_fan_frequency_setting',
    '齿轮油温度': 'gear_oil_temp',
    'EP2泵 出口压力检测': 'ep2_pump_outlet_pressure',
    'EP2 内密封压力': 'ep2_internal_seal_pressure',
    'EP2 外密封压力': 'ep2_external_seal_pressure',
    '齿轮润滑油箱压力液位1': 'gear_lubrication_tank_pressure_level1',
    '齿轮润滑油箱压力液位2': 'gear_lubrication_tank_pressure_level2',
    '泵1润滑压力': 'pump1_lubrication_pressure',
    '泵2润滑压力': 'pump2_lubrication_pressure',
    '泵3润滑压力': 'pump3_lubrication_pressure',
    '泵4润滑压力': 'pump4_lubrication_pressure',
    '齿轮密封压力': 'gear_seal_pressure',
    '齿轮回油泵出口压力': 'gear_return_oil_pump_outlet_pressure',
    '主驱动加压压力': 'main_drive_pressurisation_pressure',
    '润滑泵电机电流': 'lubrication_pump_motor_current',
    '外密封腔流量': 'external_seal_chamber_flow',
    '外密封流量': 'external_seal_flow',
    '齿轮润滑流量1': 'gear_lubrication_flow1',
    '齿轮润滑流量2': 'gear_lubrication_flow2',
    '前部小齿轮轴承润滑流量1': 'front_pinion_bearing_lube_flow1',
    '前部小齿轮轴承润滑流量2': 'front_pinion_bearing_lube_flow2',
    '后部小齿轮轴承润滑流量1': 'rear_pinion_bearing_lube_flow1',
    '后部小齿轮轴承润滑流量2': 'rear_pinion_bearing_lube_flow2',
    '齿轮密封外密封压力': 'gear_external_seal_pressure',
    '齿轮密封内密封压力': 'gear_internal_seal_pressure',
    '齿轮油温度预警设置': 'gear_oil_temp_warning_setting',
    '齿轮油温度报警设置': 'gear_oil_temp_alarm_setting',
    'EP2次数设置': 'ep2_cycle_setting',
    '主驱动1#电机电流': 'main_drive_motor1_current',
    '主驱动2#电机电流': 'main_drive_motor2_current',
    '主驱动3#电机电流': 'main_drive_motor3_current',
    '主驱动4#电机电流': 'main_drive_motor4_current',
    '主驱动5#电机电流': 'main_drive_motor5_current',
    '主驱动6#电机电流': 'main_drive_motor6_current',
    '主驱动7#电机电流': 'main_drive_motor7_current',
    '主驱动8#电机电流': 'main_drive_motor8_current',
    '主驱动9#电机电流': 'main_drive_motor9_current',
    '主驱动10#电机电流': 'main_drive_motor10_current',
    '主驱动1#电机扭矩': 'main_drive_motor1_torque',
    '主驱动2#电机扭矩': 'main_drive_motor2_torque',
    '主驱动3#电机扭矩': 'main_drive_motor3_torque',
    '主驱动4#电机扭矩': 'main_drive_motor4_torque',
    '主驱动5#电机扭矩': 'main_drive_motor5_torque',
    '主驱动6#电机扭矩': 'main_drive_motor6_torque',
    '主驱动7#电机扭矩': 'main_drive_motor7_torque',
    '主驱动8#电机扭矩': 'main_drive_motor8_torque',
    '主驱动9#电机扭矩': 'main_drive_motor9_torque',
    '主驱动10#电机扭矩': 'main_drive_motor10_torque',
    '主驱动1#电机输出频率': 'main_drive_motor1_output_frequency',
    '主驱动2#电机输出频率': 'main_drive_motor2_output_frequency',
    '主驱动3#电机输出频率': 'main_drive_motor3_output_frequency',
    '主驱动4#电机输出频率': 'main_drive_motor4_output_frequency',
    '主驱动5#电机输出频率': 'main_drive_motor5_output_frequency',
    '主驱动6#电机输出频率': 'main_drive_motor6_output_frequency',
    '主驱动7#电机输出频率': 'main_drive_motor7_output_frequency',
    '主驱动8#电机输出频率': 'main_drive_motor8_output_frequency',
    '主驱动9#电机输出频率': 'main_drive_motor9_output_frequency',
    '主驱动10#电机输出频率': 'main_drive_motor10_output_frequency',
    '主驱动1#电机输出功率': 'main_drive_motor1_output_power',
    '主驱动2#电机输出功率': 'main_drive_motor2_output_power',
    '主驱动3#电机输出功率': 'main_drive_motor3_output_power',
    '主驱动4#电机输出功率': 'main_drive_motor4_output_power',
    '主驱动5#电机输出功率': 'main_drive_motor5_output_power',
    '主驱动6#电机输出功率': 'main_drive_motor6_output_power',
    '主驱动7#电机输出功率': 'main_drive_motor7_output_power',
    '主驱动8#电机输出功率': 'main_drive_motor8_output_power',
    '主驱动9#电机输出功率': 'main_drive_motor9_output_power',
    '主驱动10#电机输出功率': 'main_drive_motor10_output_power',
    '减速机1#温度': 'gearbox1_temp',
    '减速机2#温度': 'gearbox2_temp',
    '减速机3#温度': 'gearbox3_temp',
    '减速机4#温度': 'gearbox4_temp',
    '减速机5#温度': 'gearbox5_temp',
    '减速机6#温度': 'gearbox6_temp',
    '减速机7#温度': 'gearbox7_temp',
    '减速机8#温度': 'gearbox8_temp',
    '减速机9#温度': 'gearbox9_temp',
    '减速机10#温度': 'gearbox10_temp',
    '刀盘转速-RPM': 'cutterhead_rpm',
    '刀盘转速电位器设定值': 'cutterhead_rpm_potentiometer_setting',
    '刀盘刹车压力': 'cutterhead_brake_pressure',
    '刀盘扭矩-Torque': 'cutterhead_torque',
    '刀盘给定转速显示值': 'cutterhead_target_rpm_display',
    '刀盘速度给定': 'cutterhead_target_speed',
    '刀盘功率': 'cutterhead_power',
    '刀盘运行时间': 'cutterhead_operation_time',
    '刀盘运行时间.1': 'cutterhead_operation_time_1',
    '给定频率': 'target_frequency',
    '变频柜回水温度报警值': 'inverter_cabinet_return_water_temp_alarm',
    '变频柜回水温度停机值': 'inverter_cabinet_return_water_temp_shutdown',
    '减速机温度报警值': 'gearbox_temp_alarm_value',
    '减速机温度停机值': 'gearbox_temp_shutdown_value',
    '刀盘最低转速设置': 'cutterhead_min_rpm_setting',
    '左撑靴小腔压力': 'left_shoe_small_chamber_pressure',
    '右撑靴小腔压力': 'right_shoe_small_chamber_pressure',
    '推进压力': 'propulsion_pressure',
    '贯入度-Penetration': 'penetration_rate',
    '总推进力-Force': 'total_propulsion_force',
    '推进速度-Pr': 'propulsion_speed',
    '推进位移': 'propulsion_displacement',
    '推进泵电机电流': 'propulsion_pump_motor_current',
    '撑靴泵电机电流': 'shoe_pump_motor_current',
    '换步泵电机电流': 'stepping_pump_motor_current',
    '左推进油缸行程检测': 'left_propulsion_cylinder_stroke',
    '右推进油缸行程检测': 'right_propulsion_cylinder_stroke',
    '左撑靴油缸行程检测': 'left_shoe_cylinder_stroke',
    '右撑靴油缸行程检测': 'right_shoe_cylinder_stroke',
    '推进速度电位器设定值': 'propulsion_speed_potentiometer_setting',
    '推进泵压力': 'propulsion_pump_pressure',
    '控制油路2压力检测': 'control_hydraulic_line2_pressure',
    '辅助系统压力检测': 'auxiliary_system_pressure',
    '推进速度给定百分比': 'propulsion_speed_target_percent',
    '左撑靴俯仰角': 'left_shoe_pitch_angle',
    '左撑靴滚动角': 'left_shoe_roll_angle',
    '右撑靴俯仰角': 'right_shoe_pitch_angle',
    '右撑靴滚动角': 'right_shoe_roll_angle',
    '控制泵压力': 'control_pump_pressure',
    '控制油路1 压力': 'control_hydraulic_line1_pressure',
    '换步泵1 压力': 'stepping_pump1_pressure',
    '撑靴泵压力': 'shoe_pump_pressure',
    '换步泵2 压力': 'stepping_pump2_pressure',
    '钢拱架泵压力': 'steel_arch_pump_pressure',
    '主机皮带机泵压力': 'main_conveyor_pump_pressure',
    '左倾最大滚动角设置': 'left_max_roll_angle_setting',
    '右倾最大滚动角设置': 'right_max_roll_angle_setting',
    '左撑靴最大滚动角设置': 'left_shoe_max_roll_angle_setting',
    '左撑靴最大俯仰角设置': 'left_shoe_max_pitch_angle_setting',
    '右撑靴最大滚动角设置': 'right_shoe_max_roll_angle_setting',
    '右撑靴最大俯仰角设置': 'right_shoe_max_pitch_angle_setting',
    '撑靴压力设定': 'shoe_pressure_setting',
    '推进位移最大允许偏差设置': 'propulsion_max_displacement_deviation_setting',
    '贯入度设置': 'penetration_rate_setting',
    '推进给定速度百分比': 'propulsion_target_speed_percent',
    '推进速度': 'propulsion_speed_actual',
    '刀盘CH4气体浓度': 'cutterhead_CH4_concentration',
    '刀盘H2S浓度': 'cutterhead_H2S_concentration',
    '控制室O2浓度': 'control_room_O2_concentration',
    '控制室CO浓度': 'control_room_CO_concentration',
    '控制室CO2浓度': 'control_room_CO2_concentration',
    '设备桥CH4浓度': 'equipment_bridge_CH4_concentration',
    '拖车尾部CH4浓度': 'trailer_rear_CH4_concentration',
    '左拖拉油缸压力': 'left_thruster_cylinder_pressure',
    '右拖拉油缸压力': 'right_thruster_cylinder_pressure',
    '拖拉油缸最大允许压力设置': 'thruster_cylinder_max_pressure_setting',
    '拖拉油缸最小允许压力设置': 'thruster_cylinder_min_pressure_setting',
    '机械手泵1 电机电流': 'manipulator_pump1_motor_current',
    '机械手泵2 电机电流': 'manipulator_pump2_motor_current',
    '主机皮带机转速': 'main_conveyor_speed',
    '桥架皮带机转速': 'bridge_conveyor_speed',
    '转渣皮带机转速': 'muck_transfer_conveyor_speed',
    '主机皮带机泵电机电流': 'main_conveyor_pump_motor_current',
    '主皮带机转速电位器设定值': 'main_conveyor_speed_potentiometer_setting',
    '桥架皮带机转速电位器设定值': 'bridge_conveyor_speed_potentiometer_setting',
    '转渣皮带机转速电位器设定值': 'muck_transfer_conveyor_speed_potentiometer_setting',
    'Unnamed: 198': 'unnamed_198'
    }

        # dataset specific metadata dictionaries
        self.param_dict = {'filename': 'TBM_A',
                           'n cutters': 50,
                           'cutter radius': 241.3,  # [mm]
                           'cutterhead diameter': 7,  # [m]
                           'cutterhead rotations': 6,  # [rpm]
                           'M0': 180,  # [kNm]
                           'torque ratio bounds': (0.35, 0.57),
                           'stroke length': 1.7,  # [m]
                           'frequency': 10  # frequency of datapoint recording [s]
                           }


class utilities(dictionaries):

    def __init__(self):
        super().__init__()   # calls dictionaries.__init__()

    def torque_ratio(self,
                     advance_force: pd.Series,  # cutterhead advance force [kN]
                     penetration: pd.Series,  # penetration [mm/rev]
                     torque: pd.Series  # real torque [kNm]
                     ) -> pd.Series:
        '''computation of the torque ratio according to the Austrian
        contractual standard: ÖNORM B2203-2 (2023)'''
        F_n = advance_force / self.param_dict['n cutters']
        alpha = np.arccos((self.param_dict['cutter radius'] - penetration)/self.param_dict['cutter radius'])
        F_tang = np.tan(alpha/2)*F_n
        theo_torque = 0.3 * F_tang * self.param_dict['n cutters'] * self.param_dict['cutterhead diameter'] + self.param_dict['M0']
        torque_ratio = torque / theo_torque
        return theo_torque, torque_ratio



